package com.tradinganalytics.core.constants

object AppConstants {

    object Database {
        const val NAME = "trading_analytics_db"
        const val VERSION = 1
    }

    object Preferences {
        const val NAME = "trading_analytics_prefs"
        const val ENCRYPTED_NAME = "trading_analytics_secure_prefs"
    }

    object DefaultAccounts {
        data class Account(val username: String, val password: String, val role: String, val status: String)

        val ADMIN = Account(
            username = "admin",
            password = "bypass",
            role = UserRoles.ADMIN,
            status = AccountStatus.ACTIVE
        )

        val TESTING = Account(
            username = "testing",
            password = "testing123",
            role = UserRoles.USER,
            status = AccountStatus.ACTIVE
        )
    }

    object UserRoles {
        const val ADMIN = "ADMIN"
        const val USER = "USER"

        val all = listOf(ADMIN, USER)
    }

    object AccountStatus {
        const val ACTIVE = "ACTIVE"
        const val DISABLED = "DISABLED"
        const val LOCKED = "LOCKED"
        const val DELETED = "DELETED"

        val all = listOf(ACTIVE, DISABLED, LOCKED, DELETED)
    }

    const val VERSION_NAME = "1.0.0"

    object Session {
        const val PREF_KEY_IS_LOGGED_IN = "is_logged_in"
        const val PREF_KEY_USERNAME = "session_username"
        const val PREF_KEY_USER_ROLE = "session_user_role"
        const val PREF_KEY_SESSION_TOKEN = "session_token"
        const val PREF_KEY_LOGIN_TIMESTAMP = "login_timestamp"
        const val PREF_KEY_REMEMBER_LOGIN = "remember_login"
        const val PREF_KEY_USER_ID = "user_id"

        const val TIMEOUT_DURATION_MS = 30 * 60 * 1000L
        const val EXTENDED_TIMEOUT_DURATION_MS = 24 * 60 * 60 * 1000L
    }

    object Balance {
        const val DEFAULT_BALANCE = 0.0
        const val DEFAULT_INITIAL_BALANCE = 100000.0
        const val MIN_TRADE_AMOUNT = 100.0
        const val MAX_TRADE_AMOUNT = 1000000.0
        const val DEFAULT_LEVERAGE = 1.0
        const val MAX_LEVERAGE = 100.0
    }

    object RiskLevels {
        const val LOW = "LOW"
        const val MEDIUM = "MEDIUM"
        const val HIGH = "HIGH"

        val all = listOf(LOW, MEDIUM, HIGH)

        fun riskMultiplier(level: String): Double = when (level) {
            LOW -> 0.02
            MEDIUM -> 0.05
            HIGH -> 0.10
            else -> 0.05
        }

        fun maxPositionSizeRatio(level: String): Double = when (level) {
            LOW -> 0.10
            MEDIUM -> 0.25
            HIGH -> 0.50
            else -> 0.25
        }
    }

    object Goals {
        const val TABLE_NAME = "goals"
        const val DEFAULT_DAILY_PROFIT_TARGET = 500.0
        const val DEFAULT_MONTHLY_PROFIT_TARGET = 10000.0
        const val DEFAULT_RISK_PER_TRADE = 2.0
        const val MIN_GOAL_AMOUNT = 1.0
        const val MAX_GOAL_AMOUNT = 1_000_000_000.0
    }

    object Patterns {
        data class PatternInfo(
            val id: Int,
            val category: String,
            val name: String,
            val description: String
        )

        val CANDLESTICK_PATTERNS = listOf(
            PatternInfo(1, "Candlestick", "Doji", "Open and close are nearly equal"),
            PatternInfo(2, "Candlestick", "Hammer", "Small body at top with long lower wick"),
            PatternInfo(3, "Candlestick", "Shooting Star", "Small body at bottom with long upper wick"),
            PatternInfo(4, "Candlestick", "Engulfing Bullish", "Large green candle engulfs previous red candle"),
            PatternInfo(5, "Candlestick", "Engulfing Bearish", "Large red candle engulfs previous green candle"),
            PatternInfo(6, "Candlestick", "Morning Star", "Three-candle reversal pattern at bottom"),
            PatternInfo(7, "Candlestick", "Evening Star", "Three-candle reversal pattern at top"),
            PatternInfo(8, "Candlestick", "Harami Bullish", "Small green candle inside previous large red"),
            PatternInfo(9, "Candlestick", "Harami Bearish", "Small red candle inside previous large green"),
            PatternInfo(10, "Candlestick", "Piercing Line", "Green candle closes above midpoint of previous red"),
            PatternInfo(11, "Candlestick", "Dark Cloud Cover", "Red candle closes below midpoint of previous green"),
            PatternInfo(12, "Candlestick", "Three White Soldiers", "Three consecutive long green candles"),
            PatternInfo(13, "Candlestick", "Three Black Crows", "Three consecutive long red candles"),
            PatternInfo(14, "Candlestick", "Hammer Inverted", "Small body at bottom with long upper wick"),
            PatternInfo(15, "Candlestick", "Hanging Man", "Small body at top with long lower wick, downtrend"),
            PatternInfo(16, "Candlestick", "Spinning Top", "Small body with upper and lower wicks of similar length"),
            PatternInfo(17, "Candlestick", "Marubozu", "Long candle with little or no wick"),
            PatternInfo(18, "Candlestick", "Dragonfly Doji", "Doji with very long lower wick"),
            PatternInfo(19, "Candlestick", "Gravestone Doji", "Doji with very long upper wick"),
            PatternInfo(20, "Candlestick", "Long Legged Doji", "Doji with long upper and lower wicks"),
            PatternInfo(21, "Candlestick", "Tweezer Top", "Two candles with same high at top"),
            PatternInfo(22, "Candlestick", "Tweezer Bottom", "Two candles with same low at bottom"),
            PatternInfo(23, "Candlestick", "Rising Three Methods", "Bullish continuation pattern"),
            PatternInfo(24, "Candlestick", "Falling Three Methods", "Bearish continuation pattern"),
            PatternInfo(25, "Candlestick", "Breakaway Bullish", "Five-candle bullish reversal"),
            PatternInfo(26, "Candlestick", "Breakaway Bearish", "Five-candle bearish reversal"),
            PatternInfo(27, "Candlestick", "Kicking Bullish", "Dramatic bullish reversal with gap"),
            PatternInfo(28, "Candlestick", "Kicking Bearish", "Dramatic bearish reversal with gap"),
            PatternInfo(29, "Candlestick", "Three Line Strike Bullish", "Four-candle bullish pattern"),
            PatternInfo(30, "Candlestick", "Three Line Strike Bearish", "Four-candle bearish pattern"),
            PatternInfo(31, "Candlestick", "Concealing Baby Swallow", "Four-candle bearish pattern"),
            PatternInfo(32, "Candlestick", "Upside Gap Two Crows", "Bearish reversal after gap up"),
            PatternInfo(33, "Candlestick", "Two Crows", "Three-candle bearish reversal"),
            PatternInfo(34, "Candlestick", "Three Inside Up", "Bullish three-candle reversal"),
            PatternInfo(35, "Candlestick", "Three Inside Down", "Bearish three-candle reversal"),
            PatternInfo(36, "Candlestick", "Three Outside Up", "Bullish three-candle reversal"),
            PatternInfo(37, "Candlestick", "Three Outside Down", "Bearish three-candle reversal"),
            PatternInfo(38, "Candlestick", "Separating Lines Bullish", "Bullish continuation pattern"),
            PatternInfo(39, "Candlestick", "Separating Lines Bearish", "Bearish continuation pattern"),
            PatternInfo(40, "Candlestick", "Ladder Bottom", "Five-candle bullish reversal"),
            PatternInfo(41, "Candlestick", "Ladder Top", "Five-candle bearish reversal"),
            PatternInfo(42, "Candlestick", "Stick Sandwich", "Three-candle bullish pattern"),
            PatternInfo(43, "Candlestick", "Mat Hold Bullish", "Bullish continuation with gap"),
            PatternInfo(44, "Candlestick", "Mat Hold Bearish", "Bearish continuation with gap"),
            PatternInfo(45, "Candlestick", "On Neck Bullish", "Bearish continuation pattern"),
            PatternInfo(46, "Candlestick", "On Neck Bearish", "Bearish continuation pattern"),
            PatternInfo(47, "Candlestick", "In Neck Bullish", "Bullish continuation pattern"),
            PatternInfo(48, "Candlestick", "In Neck Bearish", "Bearish continuation pattern"),
            PatternInfo(49, "Candlestick", "Thrusting Bullish", "Potential bullish reversal"),
            PatternInfo(50, "Candlestick", "Thrusting Bearish", "Potential bearish reversal"),
            PatternInfo(51, "Candlestick", "Counterattack Bullish", "Two-candle bullish reversal"),
            PatternInfo(52, "Candlestick", "Counterattack Bearish", "Two-candle bearish reversal"),
            PatternInfo(53, "Candlestick", "Belt Hold Bullish", "Long white opening marubozu"),
            PatternInfo(54, "Candlestick", "Belt Hold Bearish", "Long black opening marubozu"),
            PatternInfo(55, "Candlestick", "Closing Marubozu", "Long candle with wick only at open end"),
            PatternInfo(56, "Candlestick", "Opening Marubozu", "Long candle with wick only at close end"),
            PatternInfo(57, "Candlestick", "Upside Tasuki Gap", "Bullish continuation with gap"),
            PatternInfo(58, "Candlestick", "Downside Tasuki Gap", "Bearish continuation with gap"),
            PatternInfo(59, "Candlestick", "Three Gap Upside", "Three consecutive gaps upward"),
            PatternInfo(60, "Candlestick", "Three Gap Downside", "Three consecutive gaps downward"),
            PatternInfo(61, "Candlestick", "Side by Side White Lines", "Bullish continuation with gap"),
            PatternInfo(62, "Candlestick", "Side by Side Black Lines", "Bearish continuation with gap"),
            PatternInfo(63, "Candlestick", "Upside Gap Three Methods", "Bearish continuation after gap up"),
            PatternInfo(64, "Candlestick", "Downside Gap Three Methods", "Bullish continuation after gap down"),
            PatternInfo(65, "Candlestick", "Unique Three River Bottom", "Complex bullish reversal"),
            PatternInfo(66, "Candlestick", "Three Stars in the South", "Rare bullish reversal pattern"),
            PatternInfo(67, "Candlestick", "Upside Gap Three Crows", "Bearish pattern after gap up"),
            PatternInfo(68, "Candlestick", "Three Advancing Soldiers", "Strong bullish trend continuation"),
            PatternInfo(69, "Candlestick", "Three Declining Crows", "Strong bearish trend continuation"),
            PatternInfo(70, "Candlestick", "Concealed Bullish Engulfing", "Engulfing within a strong trend"),
            PatternInfo(71, "Candlestick", "Concealed Bearish Engulfing", "Engulfing within a strong downtrend"),
            PatternInfo(72, "Candlestick", "Double Doji", "Two consecutive doji candles"),
            PatternInfo(73, "Candlestick", "Triple Doji", "Three consecutive doji candles"),
            PatternInfo(74, "Candlestick", "Four Price Doji", "Open, high, low, close are identical"),
            PatternInfo(75, "Candlestick", "Northern Doji", "Doji at trend high after strong move"),
            PatternInfo(76, "Candlestick", "Southern Doji", "Doji at trend low after strong move"),
            PatternInfo(77, "Candlestick", "Gapping Doji", "Doji that gaps above or below"),
            PatternInfo(78, "Candlestick", "Doji Star Bullish", "Doji gaps down, potential reversal"),
            PatternInfo(79, "Candlestick", "Doji Star Bearish", "Doji gaps up, potential reversal"),
            PatternInfo(80, "Candlestick", "Long Shaven Head", "Long candle with no upper wick"),
            PatternInfo(81, "Candlestick", "Long Shaven Bottom", "Long candle with no lower wick"),
            PatternInfo(82, "Candlestick", "Short Shaven Head", "Short candle with no upper wick"),
            PatternInfo(83, "Candlestick", "Short Shaven Bottom", "Short candle with no lower wick"),
            PatternInfo(84, "Candlestick", "High Wave", "Very long wicks, small body, high volatility"),
            PatternInfo(85, "Candlestick", "Low Wave", "Very short wicks, small body, low volatility"),
            PatternInfo(86, "Candlestick", "Counter Trend", "Candle opposite to prevailing short-term trend"),
            PatternInfo(87, "Candlestick", "Inside Bar", "Candle entirely within previous candle range"),
            PatternInfo(88, "Candlestick", "Outside Bar", "Candle engulfs previous candle range"),
            PatternInfo(89, "Candlestick", "Narrow Range 1", "Narrowest range of last N bars"),
            PatternInfo(90, "Candlestick", "Narrow Range 4", "Fourth narrowest range of last N bars"),
            PatternInfo(91, "Candlestick", "Narrow Range 7", "Seventh narrowest range of last N bars"),
            PatternInfo(92, "Candlestick", "Wide Range 1", "Widest range of last N bars"),
            PatternInfo(93, "Candlestick", "Wide Range 4", "Fourth widest range of last N bars"),
            PatternInfo(94, "Candlestick", "Wide Range 7", "Seventh widest range of last N bars"),
            PatternInfo(95, "Candlestick", "Expanding Range", "Each bar has wider range than previous"),
            PatternInfo(96, "Candlestick", "Contracting Range", "Each bar has narrower range than previous"),
            PatternInfo(97, "Candlestick", "Key Reversal Up", "New low then close near high"),
            PatternInfo(98, "Candlestick", "Key Reversal Down", "New high then close near low"),
            PatternInfo(99, "Candlestick", "Momentum Reversal", "Sharp reversal with increased volume"),
            PatternInfo(100, "Candlestick", "Exhaustion", "Long wick after extended move indicates trend end"),
            PatternInfo(101, "Technical", "Support", "Price level where buying pressure exceeds selling"),
            PatternInfo(102, "Technical", "Resistance", "Price level where selling pressure exceeds buying"),
            PatternInfo(103, "Technical", "Trendline Bullish", "Upward sloping line connecting higher lows"),
            PatternInfo(104, "Technical", "Trendline Bearish", "Downward sloping line connecting lower highs"),
            PatternInfo(105, "Technical", "Channel Up", "Price between two parallel rising trendlines"),
            PatternInfo(106, "Technical", "Channel Down", "Price between two parallel falling trendlines"),
            PatternInfo(107, "Technical", "Channel Horizontal", "Price between two horizontal trendlines"),
            PatternInfo(108, "Technical", "Double Top", "Two peaks at similar level, bearish reversal"),
            PatternInfo(109, "Technical", "Double Bottom", "Two troughs at similar level, bullish reversal"),
            PatternInfo(110, "Technical", "Triple Top", "Three peaks at similar level, bearish reversal"),
            PatternInfo(111, "Technical", "Triple Bottom", "Three troughs at similar level, bullish reversal"),
            PatternInfo(112, "Technical", "Head and Shoulders", "Three peaks with middle highest, bearish"),
            PatternInfo(113, "Technical", "Inverse Head and Shoulders", "Three troughs with middle lowest, bullish"),
            PatternInfo(114, "Technical", "Rising Wedge", "Converging trendlines sloping up, bearish"),
            PatternInfo(115, "Technical", "Falling Wedge", "Converging trendlines sloping down, bullish"),
            PatternInfo(116, "Technical", "Ascending Triangle", "Horizontal resistance, rising support"),
            PatternInfo(117, "Technical", "Descending Triangle", "Horizontal support, falling resistance"),
            PatternInfo(118, "Technical", "Symmetrical Triangle", "Converging trendlines, breakout pending"),
            PatternInfo(119, "Technical", "Pennant", "Small symmetrical triangle after sharp move"),
            PatternInfo(120, "Technical", "Flag Bullish", "Small rectangle sloping against uptrend"),
            PatternInfo(121, "Technical", "Flag Bearish", "Small rectangle sloping against downtrend"),
            PatternInfo(122, "Technical", "Cup and Handle", "Rounded bottom with small pullback, bullish"),
            PatternInfo(123, "Technical", "Rounding Bottom", "Gradual U-shaped reversal pattern"),
            PatternInfo(124, "Technical", "Rounding Top", "Gradual inverted U-shaped reversal pattern"),
            PatternInfo(125, "Technical", "V Bottom", "Sharp V-shaped reversal from downtrend"),
            PatternInfo(126, "Technical", "V Top", "Sharp V-shaped reversal from uptrend"),
            PatternInfo(127, "Technical", "W Pattern", "Double bottom formation pattern"),
            PatternInfo(128, "Technical", "M Pattern", "Double top formation pattern"),
            PatternInfo(129, "Technical", "Fibonacci Retracement 0.236", "23.6% retracement level"),
            PatternInfo(130, "Technical", "Fibonacci Retracement 0.382", "38.2% retracement level"),
            PatternInfo(131, "Technical", "Fibonacci Retracement 0.500", "50.0% retracement level"),
            PatternInfo(132, "Technical", "Fibonacci Retracement 0.618", "61.8% retracement level"),
            PatternInfo(133, "Technical", "Fibonacci Retracement 0.786", "78.6% retracement level"),
            PatternInfo(134, "Technical", "Fibonacci Extension 1.272", "127.2% extension level"),
            PatternInfo(135, "Technical", "Fibonacci Extension 1.618", "161.8% extension level"),
            PatternInfo(136, "Technical", "Fibonacci Extension 2.618", "261.8% extension level"),
            PatternInfo(137, "Technical", "Fibonacci Fan", "Fan lines from Fibonacci levels"),
            PatternInfo(138, "Technical", "Fibonacci Channel", "Channel based on Fibonacci ratios"),
            PatternInfo(139, "Technical", "Fibonacci Time Zones", "Vertical lines at Fibonacci intervals"),
            PatternInfo(140, "Technical", "Fibonacci Arc", "Curved arcs at Fibonacci levels"),
            PatternInfo(141, "Technical", "Gartley 222", "Harmonic pattern with specific ratios"),
            PatternInfo(142, "Technical", "Butterfly Pattern", "Harmonic pattern with 1.618 extension"),
            PatternInfo(143, "Technical", "Bat Pattern", "Harmonic pattern with 0.886 retracement"),
            PatternInfo(144, "Technical", "Crab Pattern", "Harmonic pattern with 1.618 extension"),
            PatternInfo(145, "Technical", "Shark Pattern", "Harmonic pattern with 0.886 and 1.13"),
            PatternInfo(146, "Technical", "ABCD Pattern", "Three-leg harmonic pattern"),
            PatternInfo(147, "Technical", "Three Drives", "Harmonic pattern with three legs"),
            PatternInfo(148, "Technical", "Elliott Wave 1", "First impulsive wave in uptrend"),
            PatternInfo(149, "Technical", "Elliott Wave 2", "Corrective wave retracing wave 1"),
            PatternInfo(150, "Technical", "Elliott Wave 3", "Strongest impulsive wave"),
            PatternInfo(151, "Technical", "Elliott Wave 4", "Corrective wave retracing wave 3"),
            PatternInfo(152, "Technical", "Elliott Wave 5", "Final impulsive wave, often extended"),
            PatternInfo(153, "Technical", "Elliott Wave A", "First wave of ABC correction"),
            PatternInfo(154, "Technical", "Elliott Wave B", "Retracement of wave A"),
            PatternInfo(155, "Technical", "Elliott Wave C", "Final wave of ABC correction"),
            PatternInfo(156, "Technical", "Zigzag", "Sharp ABC correction pattern"),
            PatternInfo(157, "Technical", "Flat", "Sideways ABC correction pattern"),
            PatternInfo(158, "Technical", "Triangle", "Contracting ABCDE correction pattern"),
            PatternInfo(159, "Technical", "WXY Pattern", "Double three correction pattern"),
            PatternInfo(160, "Technical", "WXYXZ Pattern", "Triple three correction pattern"),
            PatternInfo(161, "Technical", "Ichimoku Cloud Bullish", "Price above cloud, TK cross bullish"),
            PatternInfo(162, "Technical", "Ichimoku Cloud Bearish", "Price below cloud, TK cross bearish"),
            PatternInfo(163, "Technical", "Ichimoku TK Cross", "Tenkan-sen crosses Kijun-sen"),
            PatternInfo(164, "Technical", "Ichimoku Cloud Breakout", "Price breaks through cloud boundary"),
            PatternInfo(165, "Technical", "Ichimoku Senkou Span A", "Leading span A cloud boundary"),
            PatternInfo(166, "Technical", "Ichimoku Senkou Span B", "Leading span B cloud boundary"),
            PatternInfo(167, "Technical", "Ichimoku Chikou Span", "Lagging span confirmation"),
            PatternInfo(168, "Technical", "Ichimoku Kumo Twist", "Cloud color change signal"),
            PatternInfo(169, "Technical", "Pivot Point Standard", "Standard floor pivot calculation"),
            PatternInfo(170, "Technical", "Pivot Point Fibonacci", "Fibonacci-based pivot levels"),
            PatternInfo(171, "Technical", "Pivot Point Woodie", "Woodie pivot calculation method"),
            PatternInfo(172, "Technical", "Pivot Point Camarilla", "Camarilla pivot calculation method"),
            PatternInfo(173, "Technical", "Pivot Point DeMark", "DeMark pivot calculation method"),
            PatternInfo(174, "Technical", "Pivot S1", "First support level"),
            PatternInfo(175, "Technical", "Pivot S2", "Second support level"),
            PatternInfo(176, "Technical", "Pivot S3", "Third support level"),
            PatternInfo(177, "Technical", "Pivot R1", "First resistance level"),
            PatternInfo(178, "Technical", "Pivot R2", "Second resistance level"),
            PatternInfo(179, "Technical", "Pivot R3", "Third resistance level"),
            PatternInfo(180, "Technical", "Order Block Bullish", "Large buy order price zone"),
            PatternInfo(181, "Technical", "Order Block Bearish", "Large sell order price zone"),
            PatternInfo(182, "Technical", "Breaker Block Bullish", "Broken support turned resistance"),
            PatternInfo(183, "Technical", "Breaker Block Bearish", "Broken resistance turned support"),
            PatternInfo(184, "Technical", "Mitigation Block", "Price returns to liquidity zone"),
            PatternInfo(185, "Technical", "Liquidity Sweep", "Price takes out previous low/high"),
            PatternInfo(186, "Technical", "Fair Value Gap", "Inefficient price area between candles"),
            PatternInfo(187, "Technical", "Imbalance Bullish", "Buying pressure imbalance zone"),
            PatternInfo(188, "Technical", "Imbalance Bearish", "Selling pressure imbalance zone"),
            PatternInfo(189, "Technical", "Order Flow Imbalance", "Volume delta imbalance pattern"),
            PatternInfo(190, "Technical", "Market Structure Shift", "Change in trend structure"),
            PatternInfo(191, "Technical", "Change of Character", "Abrupt change in price behavior"),
            PatternInfo(192, "Technical", "Displacement", "Strong directional price move"),
            PatternInfo(193, "Technical", "Stop Hunt", "Price moves to trigger stop losses"),
            PatternInfo(194, "Technical", "Engulfing Order Block", "Large order block engulfing previous"),
            PatternInfo(195, "Technical", "Accumulation", "Smart money buying phase"),
            PatternInfo(196, "Technical", "Distribution", "Smart money selling phase"),
            PatternInfo(197, "Technical", "Markup Phase", "Price acceleration in uptrend"),
            PatternInfo(198, "Technical", "Markdown Phase", "Price acceleration in downtrend"),
            PatternInfo(199, "Technical", "Wyckoff Spring", "Final low before markup phase"),
            PatternInfo(200, "Technical", "Wyckoff Upthrust", "Final high before markdown phase"),
            PatternInfo(201, "Indicator", "SMA Crossover Bullish", "Fast SMA crosses above slow SMA"),
            PatternInfo(202, "Indicator", "SMA Crossover Bearish", "Fast SMA crosses below slow SMA"),
            PatternInfo(203, "Indicator", "EMA Crossover Bullish", "Fast EMA crosses above slow EMA"),
            PatternInfo(204, "Indicator", "EMA Crossover Bearish", "Fast EMA crosses below slow EMA"),
            PatternInfo(205, "Indicator", "MACD Crossover Bullish", "MACD line crosses above signal line"),
            PatternInfo(206, "Indicator", "MACD Crossover Bearish", "MACD line crosses below signal line"),
            PatternInfo(207, "Indicator", "MACD Zero Cross Bullish", "MACD histogram crosses above zero"),
            PatternInfo(208, "Indicator", "MACD Zero Cross Bearish", "MACD histogram crosses below zero"),
            PatternInfo(209, "Indicator", "MACD Divergence Bullish", "Price lower low, MACD higher low"),
            PatternInfo(210, "Indicator", "MACD Divergence Bearish", "Price higher high, MACD lower high"),
            PatternInfo(211, "Indicator", "MACD Hidden Divergence Bullish", "Price higher low, MACD lower low"),
            PatternInfo(212, "Indicator", "MACD Hidden Divergence Bearish", "Price lower high, MACD higher high"),
            PatternInfo(213, "Indicator", "RSI Overbought", "RSI above 70, potential reversal down"),
            PatternInfo(214, "Indicator", "RSI Oversold", "RSI below 30, potential reversal up"),
            PatternInfo(215, "Indicator", "RSI Divergence Bullish", "Price lower low, RSI higher low"),
            PatternInfo(216, "Indicator", "RSI Divergence Bearish", "Price higher high, RSI lower high"),
            PatternInfo(217, "Indicator", "RSI Hidden Divergence Bullish", "Price higher low, RSI lower low"),
            PatternInfo(218, "Indicator", "RSI Hidden Divergence Bearish", "Price lower high, RSI higher high"),
            PatternInfo(219, "Indicator", "RSI Centerline Cross Bullish", "RSI crosses above 50"),
            PatternInfo(220, "Indicator", "RSI Centerline Cross Bearish", "RSI crosses below 50"),
            PatternInfo(221, "Indicator", "RSI Failure Swing", "RSI reversal within overbought/oversold"),
            PatternInfo(222, "Indicator", "Stochastic Overbought", "%K above 80, potential reversal"),
            PatternInfo(223, "Indicator", "Stochastic Oversold", "%K below 20, potential reversal"),
            PatternInfo(224, "Indicator", "Stochastic Crossover Bullish", "%K crosses above %D"),
            PatternInfo(225, "Indicator", "Stochastic Crossover Bearish", "%K crosses below %D"),
            PatternInfo(226, "Indicator", "Stochastic Divergence Bullish", "Bullish divergence on stochastic"),
            PatternInfo(227, "Indicator", "Stochastic Divergence Bearish", "Bearish divergence on stochastic"),
            PatternInfo(228, "Indicator", "Bollinger Band Squeeze", "Bands contract, volatility about to expand"),
            PatternInfo(229, "Indicator", "Bollinger Band Breakout Up", "Price closes above upper band"),
            PatternInfo(230, "Indicator", "Bollinger Band Breakout Down", "Price closes below lower band"),
            PatternInfo(231, "Indicator", "Bollinger Band Walk Up", "Price rides upper band in uptrend"),
            PatternInfo(232, "Indicator", "Bollinger Band Walk Down", "Price rides lower band in downtrend"),
            PatternInfo(233, "Indicator", "Bollinger Band Reversion", "Price returns to middle band"),
            PatternInfo(234, "Indicator", "Bollinger Band %B", "%B indicator value zones"),
            PatternInfo(235, "Indicator", "Bollinger Bandwidth", "Bandwidth expansion/contraction signal"),
            PatternInfo(236, "Indicator", "ATR Breakout Up", "Breakout with ATR confirmation"),
            PatternInfo(237, "Indicator", "ATR Breakout Down", "Breakdown with ATR confirmation"),
            PatternInfo(238, "Indicator", "ATR Trailing Stop", "Trailing stop based on ATR multiple"),
            PatternInfo(239, "Indicator", "ATR Channel", "Channel based on ATR around moving average"),
            PatternInfo(240, "Indicator", "OBV Trend Confirmation", "OBV confirms price trend direction"),
            PatternInfo(241, "Indicator", "OBV Divergence Bullish", "Price down, OBV up"),
            PatternInfo(242, "Indicator", "OBV Divergence Bearish", "Price up, OBV down"),
            PatternInfo(243, "Indicator", "OBV Breakout", "OBV breaks trendline before price"),
            PatternInfo(244, "Indicator", "Volume Spike", "Volume significantly above average"),
            PatternInfo(245, "Indicator", "Volume Climax", "Extreme volume indicating exhaustion"),
            PatternInfo(246, "Indicator", "Volume Dry Up", "Volume significantly below average"),
            PatternInfo(247, "Indicator", "Volume Confirmation", "Volume confirms price move direction"),
            PatternInfo(248, "Indicator", "Volume Divergence", "Price direction diverges from volume"),
            PatternInfo(249, "Indicator", "MFI Overbought", "Money Flow Index above 80"),
            PatternInfo(250, "Indicator", "MFI Oversold", "Money Flow Index below 20"),
            PatternInfo(251, "Indicator", "MFI Divergence Bullish", "Bullish divergence on MFI"),
            PatternInfo(252, "Indicator", "MFI Divergence Bearish", "Bearish divergence on MFI"),
            PatternInfo(253, "Indicator", "VWAP Bullish Cross", "Price crosses above VWAP"),
            PatternInfo(254, "Indicator", "VWAP Bearish Cross", "Price crosses below VWAP"),
            PatternInfo(255, "Indicator", "VWAP Support", "VWAP acts as support in uptrend"),
            PatternInfo(256, "Indicator", "VWAP Resistance", "VWAP acts as resistance in downtrend"),
            PatternInfo(257, "Indicator", "VWAP Deviation", "Price significantly deviates from VWAP"),
            PatternInfo(258, "Indicator", "Parabolic SAR Bullish", "SAR dots below price, uptrend"),
            PatternInfo(259, "Indicator", "Parabolic SAR Bearish", "SAR dots above price, downtrend"),
            PatternInfo(260, "Indicator", "Parabolic SAR Reversal", "SAR flips from above to below or vice versa"),
            PatternInfo(261, "Indicator", "ADX Strong Trend", "ADX above 25, strong trend present"),
            PatternInfo(262, "Indicator", "ADX Weak Trend", "ADX below 20, weak or no trend"),
            PatternInfo(263, "Indicator", "ADX Cross Bullish", "+DI crosses above -DI, ADX rising"),
            PatternInfo(264, "Indicator", "ADX Cross Bearish", "-DI crosses above +DI, ADX rising"),
            PatternInfo(265, "Indicator", "CCI Overbought", "CCI above +100"),
            PatternInfo(266, "Indicator", "CCI Oversold", "CCI below -100"),
            PatternInfo(267, "Indicator", "CCI Divergence Bullish", "Bullish divergence on CCI"),
            PatternInfo(268, "Indicator", "CCI Divergence Bearish", "Bearish divergence on CCI"),
            PatternInfo(269, "Indicator", "CCI Zero Cross Bullish", "CCI crosses above zero"),
            PatternInfo(270, "Indicator", "CCI Zero Cross Bearish", "CCI crosses below zero"),
            PatternInfo(271, "Indicator", "Williams %R Overbought", "%R above -20"),
            PatternInfo(272, "Indicator", "Williams %R Oversold", "%R below -80"),
            PatternInfo(273, "Indicator", "Williams %R Crossover", "%R crosses above/below threshold"),
            PatternInfo(274, "Indicator", "Ichimoku Cloud Conversion", "Tenkan-sen acts as support/resistance"),
            PatternInfo(275, "Indicator", "Ichimoku Cloud Base", "Kijun-sen acts as support/resistance"),
            PatternInfo(276, "Indicator", "Ichimoku Cloud Lagging", "Chikou span confirms trend direction"),
            PatternInfo(277, "Indicator", "Ichimoku Cloud Thick", "Cloud thickness indicates strength"),
            PatternInfo(278, "Indicator", "Ichimoku Cloud Thin", "Cloud thinness indicates weakness"),
            PatternInfo(279, "Indicator", "Hull MA Crossover Bullish", "Hull MA fast crosses above slow"),
            PatternInfo(280, "Indicator", "Hull MA Crossover Bearish", "Hull MA fast crosses below slow"),
            PatternInfo(281, "Indicator", "KAMA Crossover Bullish", "Kaufman AMA crosses above price"),
            PatternInfo(282, "Indicator", "KAMA Crossover Bearish", "Kaufman AMA crosses below price"),
            PatternInfo(283, "Indicator", "TEMA Crossover Bullish", "Triple EMA crossover bullish"),
            PatternInfo(284, "Indicator", "TEMA Crossover Bearish", "Triple EMA crossover bearish"),
            PatternInfo(285, "Indicator", "WMA Crossover Bullish", "Weighted MA crossover bullish"),
            PatternInfo(286, "Indicator", "WMA Crossover Bearish", "Weighted MA crossover bearish"),
            PatternInfo(287, "Indicator", "VWMA Crossover Bullish", "Volume weighted MA crossover bullish"),
            PatternInfo(288, "Indicator", "VWMA Crossover Bearish", "Volume weighted MA crossover bearish"),
            PatternInfo(289, "Indicator", "ALMA Crossover Bullish", "Arnaud Legoux MA crossover bullish"),
            PatternInfo(290, "Indicator", "ALMA Crossover Bearish", "Arnaud Legoux MA crossover bearish"),
            PatternInfo(291, "Indicator", "Supertrend Bullish", "Supertrend indicator below price"),
            PatternInfo(292, "Indicator", "Supertrend Bearish", "Supertrend indicator above price"),
            PatternInfo(293, "Indicator", "Supertrend Reversal", "Supertrend flips direction"),
            PatternInfo(294, "Indicator", "Pivot SAR Bullish", "Parabolic SAR on pivots bullish"),
            PatternInfo(295, "Indicator", "Pivot SAR Bearish", "Parabolic SAR on pivots bearish"),
            PatternInfo(296, "Indicator", "ZLEMA Crossover Bullish", "Zero lag EMA crossover bullish"),
            PatternInfo(297, "Indicator", "ZLEMA Crossover Bearish", "Zero lag EMA crossover bearish"),
            PatternInfo(298, "Indicator", "RMA Crossover Bullish", "Moving average crossover bullish"),
            PatternInfo(299, "Indicator", "RMA Crossover Bearish", "Moving average crossover bearish"),
            PatternInfo(300, "Indicator", "PPO Crossover Bullish", "Percentage price oscillator bullish cross"),
            PatternInfo(301, "Statistical", "Mean Reversion", "Price deviates significantly from mean"),
            PatternInfo(302, "Statistical", "Standard Deviation Channel", "Channel based on standard deviations"),
            PatternInfo(303, "Statistical", "Z-Score Extreme", "Z-score exceeds 2 or -2 threshold"),
            PatternInfo(304, "Statistical", "Correlation Break", "Correlation between assets breaks down"),
            PatternInfo(305, "Statistical", "Regression Channel", "Linear regression channel breakout"),
            PatternInfo(306, "Statistical", "Seasonality Pattern", "Repeating seasonal price pattern"),
            PatternInfo(307, "Statistical", "Momentum Factor", "Price momentum exceeds threshold"),
            PatternInfo(308, "Statistical", "Mean Absolute Deviation", "Price MAD exceeds historical threshold"),
            PatternInfo(309, "Statistical", "Skewness Extreme", "Return distribution skewness abnormal"),
            PatternInfo(310, "Statistical", "Kurtosis Extreme", "Return distribution kurtosis abnormal"),
            PatternInfo(311, "Statistical", "Volatility Cluster", "High volatility period detected"),
            PatternInfo(312, "Statistical", "Serial Correlation", "Autocorrelation in returns detected"),
            PatternInfo(313, "Statistical", "Half-Life Mean Reversion", "Mean reversion half-life calculated"),
            PatternInfo(314, "Statistical", "Cointegration Pair", "Two assets are cointegrated"),
            PatternInfo(315, "Statistical", "Stationarity Change", "Asset stationarity status changes"),
            PatternInfo(316, "Statistical", "Kalman Filter Trend", "Kalman filter extracted trend signal"),
            PatternInfo(317, "Statistical", "Hurst Exponent", "Hurst exponent indicates trend/mean reversion"),
            PatternInfo(318, "Statistical", "Entropy Regime", "Market entropy indicates regime change"),
            PatternInfo(319, "Statistical", "Fractal Dimension", "Fractal dimension changes significantly"),
            PatternInfo(320, "Statistical", "Chaikin Oscillator", "Accumulation/distribution oscillator crossover"),
            PatternInfo(321, "Statistical", "Elder Ray Bullish", "Bull power positive, bear power negative"),
            PatternInfo(322, "Statistical", "Elder Ray Bearish", "Bull power negative, bear power positive"),
            PatternInfo(323, "Statistical", "Force Index Bullish", "Force index positive above threshold"),
            PatternInfo(324, "Statistical", "Force Index Bearish", "Force index negative below threshold"),
            PatternInfo(325, "Statistical", "Ease of Movement", "Ease of movement ratio signal"),
            PatternInfo(326, "Statistical", "Detrended Price", "Price detached from long-term trend"),
            PatternInfo(327, "Statistical", "Vertical Horizontal Filter", "VHF indicates trending vs ranging market"),
            PatternInfo(328, "Statistical", "Chande Momentum Oscillator", "CMO exceeds threshold levels"),
            PatternInfo(329, "Statistical", "Choppiness Index", "Market choppiness zone indicator"),
            PatternInfo(330, "Statistical", "Klinger Oscillator", "Volume force based crossover signal"),
            PatternInfo(331, "Statistical", "Know Sure Thing", "KST line crossover signal"),
            PatternInfo(332, "Statistical", "McClellan Oscillator", "Market breadth oscillator signal"),
            PatternInfo(333, "Statistical", "Arms Index", "TRIN extreme value indicator"),
            PatternInfo(334, "Statistical", "Cumulative Tick", "Tick index accumulation divergence"),
            PatternInfo(335, "Statistical", "Tick Index Extreme", "Tick index exceeds extreme thresholds"),
            PatternInfo(336, "Statistical", "Put Call Ratio Extreme", "Put/call ratio at extreme level"),
            PatternInfo(337, "Statistical", "VIX Term Structure", "VIX futures contango/backwardation"),
            PatternInfo(338, "Statistical", "Skew Index", "Option implied skew extreme level"),
            PatternInfo(339, "Statistical", "Gamma Exposure", "Dealer gamma positioning signal"),
            PatternInfo(340, "Statistical", "Delta Exposure", "Dealer delta positioning signal"),
            PatternInfo(341, "Statistical", "Open Interest Change", "Significant open interest shift"),
            PatternInfo(342, "Statistical", "Basis Spread", "Futures basis spread extreme"),
            PatternInfo(343, "Statistical", "Funding Rate Extreme", "Perpetual funding rate at extreme"),
            PatternInfo(344, "Statistical", "Liquidations Cascade", "Consecutive liquidations detected"),
            PatternInfo(345, "Statistical", "Long Short Ratio", "Long/short position ratio extreme"),
            PatternInfo(346, "Statistical", "Social Sentiment", "Social media sentiment extreme shift"),
            PatternInfo(347, "Statistical", "News Sentiment", "News sentiment analysis signal"),
            PatternInfo(348, "Statistical", "Order Flow Imbalance", "Buy/sell order flow imbalance"),
            PatternInfo(349, "Statistical", "Depth Imbalance", "Order book depth imbalance signal"),
            PatternInfo(350, "Statistical", "Bid Ask Spread", "Spread widening indicates stress"),
            PatternInfo(351, "Swing", "Bull Flag Continuation", "Flag pattern in uptrend continues"),
            PatternInfo(352, "Swing", "Bear Flag Continuation", "Flag pattern in downtrend continues"),
            PatternInfo(353, "Swing", "Pullback Reversal Bullish", "Pullback in uptrend, resuming up"),
            PatternInfo(354, "Swing", "Pullback Reversal Bearish", "Pullback in downtrend, resuming down"),
            PatternInfo(355, "Swing", "Breakout Retest Bullish", "Breakout above resistance, retests as support"),
            PatternInfo(356, "Swing", "Breakout Retest Bearish", "Breakdown below support, retests as resistance"),
            PatternInfo(357, "Swing", "Momentum Shift", "Momentum oscillator shifts direction"),
            PatternInfo(358, "Swing", "Trend Exhaustion", "Trend shows signs of ending"),
            PatternInfo(359, "Swing", "Trend Acceleration", "Trend velocity increases sharply"),
            PatternInfo(360, "Swing", "Consolidation Breakout", "Price breaks from consolidation range"),
            PatternInfo(361, "Swing", "Volume Expansion", "Volume expands as price moves"),
            PatternInfo(362, "Swing", "Volatility Expansion", "Volatility expands after contraction"),
            PatternInfo(363, "Swing", "Gap Fill Bullish", "Price fills gap and continues upward"),
            PatternInfo(364, "Swing", "Gap Fill Bearish", "Price fills gap and continues downward"),
            PatternInfo(365, "Swing", "Opening Range Breakout", "Breakout from opening range high/low"),
            PatternInfo(366, "Swing", "Closing Price Reversal", "Close reverses from intraday extreme"),
            PatternInfo(367, "Swing", "Range Expansion", "Daily range expands significantly"),
            PatternInfo(368, "Swing", "Range Contraction", "Daily range contracts significantly"),
            PatternInfo(369, "Swing", "Inside Day Breakout", "Price breaks from inside day range"),
            PatternInfo(370, "Swing", "Outside Day Reversal", "Outside day with close at opposite end"),
            PatternInfo(371, "Swing", "Two Day Reversal", "Two consecutive opposite direction days"),
            PatternInfo(372, "Swing", "Three Day Reversal", "Three day pattern reversal signal"),
            PatternInfo(373, "Swing", "Island Reversal", "Gap reversal with island formation"),
            PatternInfo(374, "Swing", "Exhaustion Gap", "Gap after extended move, trend ending"),
            PatternInfo(375, "Swing", "Runaway Gap", "Gap in middle of trend, continuation"),
            PatternInfo(376, "Swing", "Breakaway Gap", "Gap out of consolidation, trend start"),
            PatternInfo(377, "Swing", "Common Gap", "Gap with no special significance"),
            PatternInfo(378, "Swing", "Gap and Go Bullish", "Price gaps and continues in gap direction"),
            PatternInfo(379, "Swing", "Gap and Go Bearish", "Price gaps and continues in gap direction"),
            PatternInfo(380, "Swing", "Gap and Reverse Bullish", "Price gaps but reverses upward"),
            PatternInfo(381, "Swing", "Gap and Reverse Bearish", "Price gaps but reverses downward"),
            PatternInfo(382, "Swing", "Momentum Ignition", "Sharp price spike with volume surge"),
            PatternInfo(383, "Swing", "Absorption Pattern", "Large orders being absorbed at level"),
            PatternInfo(384, "Swing", "Iceberg Detection", "Hidden large order on order book"),
            PatternInfo(385, "Swing", "Spoofing Detection", "Fake orders detected on order book"),
            PatternInfo(386, "Swing", "Wash Trading Detection", "Suspicious wash trading activity"),
            PatternInfo(387, "Swing", "Pump and Dump", "Potential manipulation pattern detected"),
            PatternInfo(388, "Swing", "Order Slicing", "Large order split into smaller pieces"),
            PatternInfo(389, "Swing", "Dark Pool Activity", "Off-exchange trading volume spike"),
            PatternInfo(390, "Swing", "Cross Exchange Arbitrage", "Price difference across exchanges"),
            PatternInfo(391, "Swing", "Latency Arbitrage", "Latency-based arbitrage opportunity"),
            PatternInfo(392, "Swing", "Statistical Arbitrage", "Statistical mispricing between assets"),
            PatternInfo(393, "Swing", "Triangular Arbitrage", "Three-asset arbitrage opportunity"),
            PatternInfo(394, "Swing", "Funding Rate Arbitrage", "Perpetual vs spot basis trade"),
            PatternInfo(395, "Swing", "Index Rebalancing", "Index rebalancing price effect detected"),
            PatternInfo(396, "Swing", "Dividend Capture", "Dividend capture strategy opportunity"),
            PatternInfo(397, "Swing", "Earnings Momentum", "Post-earnings drift momentum"),
            PatternInfo(398, "Swing", "News Spike", "Sudden price move on news catalyst"),
            PatternInfo(399, "Swing", "Economic Data Release", "Reaction to economic data release"),
            PatternInfo(400, "Swing", "Central Bank Event", "Price action around central bank decision"),
            PatternInfo(401, "Custom", "Trend Strength Convergence", "Multiple trend indicators agree"),
            PatternInfo(402, "Custom", "Trend Strength Divergence", "Multiple trend indicators disagree"),
            PatternInfo(403, "Custom", "Oversold Bounce", "Oversold condition with reversal confirmation"),
            PatternInfo(404, "Custom", "Overbought Pullback", "Overbought condition with pullback signal"),
            PatternInfo(405, "Custom", "Multi-Timeframe Alignment Up", "Bullish across all timeframes"),
            PatternInfo(406, "Custom", "Multi-Timeframe Alignment Down", "Bearish across all timeframes"),
            PatternInfo(407, "Custom", "Confluence Zone", "Multiple technical levels at same price"),
            PatternInfo(408, "Custom", "Sniper Entry", "Pinpoint precision entry setup"),
            PatternInfo(409, "Custom", "Scalp Setup", "Quick small profit opportunity"),
            PatternInfo(410, "Custom", "Swing Entry", "Multi-day swing trade setup"),
            PatternInfo(411, "Custom", "Position Entry", "Long-term position trade setup"),
            PatternInfo(412, "Custom", "Risk Reward Setup", "Favorable risk-reward ratio detected"),
            PatternInfo(413, "Custom", "Stop Loss Placement", "Optimal stop loss level identified"),
            PatternInfo(414, "Custom", "Take Profit Target", "Optimal take profit level identified"),
            PatternInfo(415, "Custom", "Position Sizing Signal", "Optimal position size calculated"),
            PatternInfo(416, "Custom", "Pyramiding Signal", "Add to existing position opportunity"),
            PatternInfo(417, "Custom", "DCA Opportunity", "Dollar cost average entry identified"),
            PatternInfo(418, "Custom", "Hedge Signal", "Hedging opportunity identified"),
            PatternInfo(419, "Custom", "Pairs Trade", "Long/short pair trade setup"),
            PatternInfo(420, "Custom", "Mean Reversion Entry", "Entry at statistical extreme"),
            PatternInfo(421, "Custom", "Trend Following Entry", "Entry in direction of trend"),
            PatternInfo(422, "Custom", "Counter Trend Entry", "Entry against prevailing trend"),
            PatternInfo(423, "Custom", "Breakout Entry", "Entry on breakout confirmation"),
            PatternInfo(424, "Custom", "Pullback Entry", "Entry on pullback within trend"),
            PatternInfo(425, "Custom", "Continuation Entry", "Entry on trend continuation signal"),
            PatternInfo(426, "Custom", "Reversal Entry", "Entry on trend reversal confirmation"),
            PatternInfo(427, "Custom", "Gap Entry", "Entry based on gap strategy"),
            PatternInfo(428, "Custom", "News Entry", "Entry based on news catalyst"),
            PatternInfo(429, "Custom", "Time Based Entry", "Entry based on time of day"),
            PatternInfo(430, "Custom", "Session Based Entry", "Entry based on trading session"),
            PatternInfo(431, "Custom", "London Session Open", "Entry during London session open"),
            PatternInfo(432, "Custom", "New York Session Open", "Entry during NY session open"),
            PatternInfo(433, "Custom", "Asian Session Open", "Entry during Asian session open"),
            PatternInfo(434, "Custom", "Session Overlap", "Entry during market session overlap"),
            PatternInfo(435, "Custom", "Pre Market Pattern", "Pattern during pre-market trading"),
            PatternInfo(436, "Custom", "Post Market Pattern", "Pattern during after-hours trading"),
            PatternInfo(437, "Custom", "Opening Range Pattern", "First 30-60 minute range pattern"),
            PatternInfo(438, "Custom", "Closing Range Pattern", "Last 30-60 minute range pattern"),
            PatternInfo(439, "Custom", "Lunch Break Pattern", "Midday trading pattern"),
            PatternInfo(440, "Custom", "Weekend Gap Pattern", "Monday opening gap pattern"),
            PatternInfo(441, "Custom", "Month End Pattern", "End of month trading pattern"),
            PatternInfo(442, "Custom", "Quarter End Pattern", "End of quarter rebalancing"),
            PatternInfo(443, "Custom", "Year End Pattern", "End of year seasonal pattern"),
            PatternInfo(444, "Custom", "Holiday Pattern", "Pre/post holiday trading pattern"),
            PatternInfo(445, "Custom", "Rolling Settlement", "Futures roll period pattern"),
            PatternInfo(446, "Custom", "Expiry Pattern", "Options/futures expiry week pattern"),
            PatternInfo(447, "Custom", "Triple Witching", "Quarterly futures/options expiry pattern"),
            PatternInfo(448, "Custom", "COT Report Pattern", "Commitment of traders report reaction"),
            PatternInfo(449, "Custom", "CPI Release Pattern", "CPI data release reaction pattern"),
            PatternInfo(450, "Custom", "FOMC Pattern", "FOMC decision day pattern"),
            PatternInfo(451, "Custom", "Nonfarm Payrolls Pattern", "NFP release reaction pattern"),
            PatternInfo(452, "Custom", "GDP Release Pattern", "GDP data release reaction pattern"),
            PatternInfo(453, "Custom", "Retail Sales Pattern", "Retail sales data reaction pattern"),
            PatternInfo(454, "Custom", "Industrial Production Pattern", "Industrial production data reaction"),
            PatternInfo(455, "Custom", "PMI Release Pattern", "PMI data release reaction"),
            PatternInfo(456, "Custom", "Jobless Claims Pattern", "Weekly jobless claims reaction"),
            PatternInfo(457, "Custom", "Treasury Auction Pattern", "Treasury auction result reaction"),
            PatternInfo(458, "Custom", "Currency Intervention", "Central bank intervention pattern"),
            PatternInfo(459, "Custom", "Capital Flow Pattern", "Cross-border capital flow signal"),
            PatternInfo(460, "Custom", "Yield Curve Shift", "Yield curve movement pattern"),
            PatternInfo(461, "Custom", "Spread Widening", "Credit spread widening signal"),
            PatternInfo(462, "Custom", "Spread Narrowing", "Credit spread narrowing signal"),
            PatternInfo(463, "Custom", "Risk On Rotation", "Capital rotating into risk assets"),
            PatternInfo(464, "Custom", "Risk Off Rotation", "Capital rotating into safe havens"),
            PatternInfo(465, "Custom", "Sector Rotation", "Capital rotating between sectors"),
            PatternInfo(466, "Custom", "Factor Rotation", "Factor-based rotation pattern"),
            PatternInfo(467, "Custom", "Style Rotation", "Growth vs value rotation pattern"),
            PatternInfo(468, "Custom", "Market Cap Rotation", "Large vs small cap rotation pattern"),
            PatternInfo(469, "Custom", "Divergence Convergence", "Multiple asset divergence signal"),
            PatternInfo(470, "Custom", "Intermarket Analysis", "Cross-market relationship signal"),
            PatternInfo(471, "Custom", "Commodity Currency Link", "Commodity/currency correlation signal"),
            PatternInfo(472, "Custom", "Stock Bond Correlation", "Stock-bond correlation shift signal"),
            PatternInfo(473, "Custom", "Gold Dollar Correlation", "Gold/USD correlation break signal"),
            PatternInfo(474, "Custom", "Oil Equities Correlation", "Oil/equity correlation pattern"),
            PatternInfo(475, "Custom", "Crypto Dominance", "BTC dominance shift signal"),
            PatternInfo(476, "Custom", "Altcoin Season Signal", "Altcoin outperformance pattern"),
            PatternInfo(477, "Custom", "Stablecoin Flow", "Stablecoin supply movement signal"),
            PatternInfo(478, "Custom", "Exchange Flow", "Exchange inflow/outflow pattern"),
            PatternInfo(479, "Custom", "Miner Flow", "Miner Bitcoin flow pattern"),
            PatternInfo(480, "Custom", "Whale Movement", "Large wallet movement detected"),
            PatternInfo(481, "Custom", "Smart Money Flow", "Smart money wallet pattern"),
            PatternInfo(482, "Custom", "DeFi Protocol Flow", "DeFi TVL change pattern"),
            PatternInfo(483, "Custom", "NFT Market Pattern", "NFT market activity pattern"),
            PatternInfo(484, "Custom", "Layer 2 Activity", "L2 network activity pattern"),
            PatternInfo(485, "Custom", "Cross Chain Flow", "Bridge activity between chains"),
            PatternInfo(486, "Custom", "Gas Price Pattern", "Network gas price pattern"),
            PatternInfo(487, "Custom", "Staking Yield Pattern", "Staking yield change signal"),
            PatternInfo(488, "Custom", "Lending Rate Pattern", "Lending/borrowing rate pattern"),
            PatternInfo(489, "Custom", "Liquidation Cluster", "Clustered liquidations detected"),
            PatternInfo(490, "Custom", "Funding Rate Pattern", "Funding rate convergence/divergence"),
            PatternInfo(491, "Custom", "Open Interest Pattern", "OI change with price direction"),
            PatternInfo(492, "Custom", "Basis Trade Pattern", "Basis trading opportunity signal"),
            PatternInfo(493, "Custom", "Cash and Carry", "Cash and carry arbitrage signal"),
            PatternInfo(494, "Custom", "Premium Discount Pattern", "ETF premium/discount signal"),
            PatternInfo(495, "Custom", "NAV Deviation", "NAV deviation extreme pattern"),
            PatternInfo(496, "Custom", "Rebalancing Flow", "Portfolio rebalancing flow detected"),
            PatternInfo(497, "Custom", "Hedge Unwind", "Large hedge position unwinding"),
            PatternInfo(498, "Custom", "Short Squeeze", "Short squeeze conditions detected"),
            PatternInfo(499, "Custom", "Long Squeeze", "Long squeeze conditions detected"),
            PatternInfo(500, "Custom", "Liquidity Grab", "Liquidity grab before trend move")
        )

        val allPatterns: List<PatternInfo> get() = CANDLESTICK_PATTERNS

        fun getPatternById(id: Int): PatternInfo? = allPatterns.find { it.id == id }

        fun getPatternsByCategory(category: String): List<PatternInfo> =
            allPatterns.filter { it.category.equals(category, ignoreCase = true) }

        val categories: List<String> get() = allPatterns.map { it.category }.distinct()
    }
}
